---
  version: '3.5'

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key

  services:
    aqcu-gateway:
      build: .
      image: aqcu-gateway-service
      ports:
        - "8443:8443"
      secrets:
        - source: tomcat_ssl_crt
          target: /tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /tomcat-wildcard-ssl.key
      env_file:
        - docker-compose-default.env
